### ISSUE TITLE
 parse.y:44.21-27: syntax error, unexpected identifier

### ISSUE THREAD

**Issue by ApoorvaLandge** [pvn-leo/mini-compiler#1]
I am getting error parse.y:44.21-27: syntax error, unexpected identifier, 

In cmd I typed bison -d parse.y.

can you tell what is the error

**Comment by pvn-leo** [comment]
Try running any shell script under that directory. 
`sh <script_name>.sh`
The commands in the script are what you should be running.
Also, the input file should look similar to the input files we have tested, since this is only a minor implementation of a c++ compiler.

If it still doesn't help, paste the sample input code here, and mention what are you trying to run.

**Comment by pvn-a** [comment]
> I am getting error parse.y:44.21-27: syntax error, unexpected identifier,
> 
> In cmd I typed bison -d parse.y.
> 
> can you tell what is the error

Try running any shell script under that directory.
`sh <script_name>.sh`
The commands in the script are what you should be running.
Also, the input file should look similar to the input files we have tested, since this is only a minor implementation of a c++ compiler.

If it still doesn't help, paste the sample input code here, and mention what are you trying to run.

**Comment by ApoorvaLandge** [comment]
-
![Capture](https://user-images.githubusercontent.com/54698798/119253088-1f22db80-bbcd-11eb-9e66-9355d1753f02.JPG)

**Comment by ApoorvaLandge** [comment]
i have bison 2.xx version

**Comment by ApoorvaLandge** [comment]
i am getting error on this line
![Capture](https://user-images.githubusercontent.com/54698798/119253283-1b438900-bbce-11eb-8b3e-70116af6fce6.JPG)

**Comment by pvn-a** [comment]
So far I think, one of these might be the reason:
- You might have to _update your bison version_
- Since this was compiled and tested using Yacc software, there might be some differences in the way, Bison handles it

This mini-compiler was built using lex (**flex 2.6.4**) & yacc (**bison (GNU Bison) 3.5.1**)versions. 
I think updating your bison version to 3.5 and above, might solve this issue.

**Comment by ApoorvaLandge** [comment]
can you send me the link for bison 3.5.1  or tell where i can download
i have searched but i not getting it.

thanks for help buddy in advance

**Comment by pvn-a** [comment]
https://ftp.gnu.org/gnu/bison/

**Comment by ApoorvaLandge** [comment]
sorry to irritate  to once but is important can tell how to install gnu bison 3.5.1 in windows

**Comment by pvn-a** [comment]
https://sourceforge.net/projects/winflexbison/files/win_flex_bison3-latest.zip/download
If this doesn't help, then you will have to search for alternatives yourself.
